name: Bootcamp worlflow

on: push

jobs:
    job1:
        name: First job
        runs-on: Fedora-latest
        steps:
        - name: Step One
          uses: actions/checkout@v2
        - name: Step two
          run: env | sort
